from fastapi import FastAPI
import os
import re
import base64
import io
import json
import httpx

app = FastAPI()

FONTS_DIR = "/app/fonts"

# ============================================================
# UTILITIES
# ============================================================

def get_font_list():
    """Get all available .ttf fonts."""
    fonts = []
    if os.path.exists(FONTS_DIR):
        for f in sorted(os.listdir(FONTS_DIR)):
            if f.endswith(".ttf"):
                fonts.append(f)
    return fonts


def compress_for_output(image_data, max_bytes=2_000_000):
    """Compress final image for n8n response. Keeps under ~3MB base64."""
    from PIL import Image as PILImage
    if len(image_data) <= max_bytes:
        return base64.b64encode(image_data).decode(), "png"
    img = PILImage.open(io.BytesIO(image_data)).convert("RGB")
    for quality in [90, 80, 70, 60]:
        buf = io.BytesIO()
        img.save(buf, format="JPEG", quality=quality)
        if buf.tell() <= max_bytes:
            return base64.b64encode(buf.getvalue()).decode(), "jpeg"
    img = img.resize((int(img.width * 0.7), int(img.height * 0.7)), PILImage.LANCZOS)
    buf = io.BytesIO()
    img.save(buf, format="JPEG", quality=70)
    return base64.b64encode(buf.getvalue()).decode(), "jpeg"


def compress_for_vision(image_bytes, max_bytes=3_000_000):
    """Compress image for sending to GPT-4o Vision API."""
    from PIL import Image as PILImage
    if len(image_bytes) <= max_bytes:
        return base64.b64encode(image_bytes).decode(), "png"
    img = PILImage.open(io.BytesIO(image_bytes)).convert("RGB")
    img = img.resize((int(img.width * 0.5), int(img.height * 0.5)), PILImage.LANCZOS)
    buf = io.BytesIO()
    img.save(buf, format="JPEG", quality=80)
    return base64.b64encode(buf.getvalue()).decode(), "jpeg"


def parse_json_response(text):
    """Extract JSON from a GPT response that might have markdown fences."""
    json_match = re.search(r'```(?:json)?\s*(.*?)```', text, re.DOTALL)
    if json_match:
        return json.loads(json_match.group(1))
    # Try parsing the whole thing
    # Strip any leading/trailing whitespace or text before {
    brace_start = text.find('{')
    if brace_start >= 0:
        return json.loads(text[brace_start:])
    return json.loads(text)


def openai_headers():
    return {
        "Authorization": f"Bearer {os.environ['OPENAI_API_KEY']}",
        "Content-Type": "application/json"
    }


# ============================================================
# PASS 1 — IMAGE GENERATION (gpt-image-1)
# ============================================================

def generate_poster_image(brief, work_type):
    """Generate the poster visual with gpt-image-1. No text in image."""
    size_map = {
        "poster": "1024x1536",
        "social": "1024x1024",
        "logo": "1024x1024"
    }
    size = size_map.get(work_type, "1024x1536")

    image_prompt = f"""Create a professional {work_type} design background.

CRITICAL: Do NOT include any text, letters, numbers, words, or typography ANYWHERE in the image. Zero text. This is purely the visual layer.

Leave the top 15% and bottom 20% slightly darker, simpler, or with negative space — text will be overlaid there later and needs to be readable.

Visual direction:
{brief}

Style: Professional graphic design, high production value, intentional composition, editorial quality. This should look like it was made by a top design studio, not generated by AI."""

    response = httpx.post(
        "https://api.openai.com/v1/images/generations",
        headers=openai_headers(),
        json={
            "model": "gpt-image-1",
            "prompt": image_prompt,
            "n": 1,
            "size": size,
            "quality": "medium"
        },
        timeout=120.0
    )
    response.raise_for_status()
    data = response.json()
    return base64.b64decode(data["data"][0]["b64_json"])


# ============================================================
# PASS 2 — TEXT PLACEMENT (GPT-4o Vision)
# ============================================================

def get_text_placement(image_bytes, brief, work_type, font_list):
    """GPT-4o sees the generated image and decides exactly where text goes."""
    img_b64, img_fmt = compress_for_vision(image_bytes)
    media_type = f"image/{img_fmt}"

    prompt = f"""You are a typography director at a top design studio. You see a {work_type} background image (no text on it yet). Your job: decide exactly where text goes, what fonts to use, and what colors will read well against this specific image.

DESIGN BRIEF:
{brief}

WORK TYPE: {work_type}

AVAILABLE FONTS (use exact filenames from this list):
{font_list}

Font guidance:
- Bold display titles: BigShoulders, YoungSerif, EricaOne, Boldonse, Gloock
- Clean sans: WorkSans, Outfit, InstrumentSans, BricolageGrotesque
- Elegant serif: InstrumentSerif, LibreBaskerville, Lora, CrimsonPro, Italiana
- Mono/technical: JetBrainsMono, IBMPlexMono, GeistMono
- Thin/minimal: PoiretOne, SmoochSans, Jura

ANALYZE THE IMAGE:
- Where are the dark areas? (good for light text)
- Where are the light areas? (good for dark text)
- Where is the visual focus? (don't cover it)
- Where is breathing room? (put text there)

OUTPUT this exact JSON structure:
{{
  "overlay": {{
    "type": "none|gradient_top|gradient_bottom|darken_all",
    "opacity": 0.3,
    "color": [0, 0, 0]
  }},
  "texts": [
    {{
      "content": "EXACT TEXT STRING FROM BRIEF",
      "role": "title",
      "x_percent": 8,
      "y_percent": 5,
      "max_width_percent": 84,
      "font_file": "WorkSans-Bold.ttf",
      "size_percent": 12,
      "color_hex": "#FFFFFF",
      "align": "left"
    }}
  ]
}}

RULES:
- size_percent = text height as % of canvas height. Title: 8-15%. Subtitle: 3-5%. Details: 1.5-3%.
- x/y_percent = position from top-left corner as % of canvas dimensions.
- max_width_percent = maximum text width as % of canvas width.
- Extract ALL text from the brief. Title is always the biggest. Don't invent text not in the brief.
- If background is busy where text goes, set overlay to improve readability.
- Pick 2-3 fonts maximum. One for titles, one for details. Don't mix too many.
- Be bold with the title — it should dominate.
- Output ONLY valid JSON. No explanations."""

    response = httpx.post(
        "https://api.openai.com/v1/chat/completions",
        headers=openai_headers(),
        json={
            "model": "gpt-4o",
            "messages": [{
                "role": "user",
                "content": [
                    {
                        "type": "image_url",
                        "image_url": {
                            "url": f"data:{media_type};base64,{img_b64}"
                        }
                    },
                    {"type": "text", "text": prompt}
                ]
            }],
            "max_tokens": 2048
        },
        timeout=60.0
    )
    response.raise_for_status()
    text = response.json()["choices"][0]["message"]["content"]
    return parse_json_response(text)


# ============================================================
# PASS 3 — RENDER TEXT (PIL)
# ============================================================

def render_text_on_image(image_bytes, placement):
    """Composite text onto the poster image using PIL."""
    from PIL import Image as PILImage, ImageDraw, ImageFont
    import numpy as np

    img = PILImage.open(io.BytesIO(image_bytes)).convert("RGBA")
    width, height = img.size

    # --- Apply overlay for text readability ---
    overlay_spec = placement.get("overlay", {})
    overlay_type = overlay_spec.get("type", "none")
    if overlay_type != "none":
        opacity = overlay_spec.get("opacity", 0.3)
        oc = tuple(overlay_spec.get("color", [0, 0, 0]))
        overlay = PILImage.new("RGBA", (width, height), (0, 0, 0, 0))

        if overlay_type == "gradient_top":
            arr = np.zeros((height, width, 4), dtype=np.uint8)
            zone = int(height * 0.35)
            for y in range(zone):
                a = int(255 * opacity * (1 - y / zone))
                arr[y, :] = [oc[0], oc[1], oc[2], a]
            overlay = PILImage.fromarray(arr, "RGBA")

        elif overlay_type == "gradient_bottom":
            arr = np.zeros((height, width, 4), dtype=np.uint8)
            start = int(height * 0.65)
            zone = height - start
            for y in range(start, height):
                a = int(255 * opacity * ((y - start) / zone))
                arr[y, :] = [oc[0], oc[1], oc[2], a]
            overlay = PILImage.fromarray(arr, "RGBA")

        elif overlay_type == "darken_all":
            a = int(255 * opacity)
            overlay = PILImage.new("RGBA", (width, height), (oc[0], oc[1], oc[2], a))

        img = PILImage.alpha_composite(img, overlay)

    # --- Place text elements ---
    draw = ImageDraw.Draw(img)

    for text_spec in placement.get("texts", []):
        content = str(text_spec.get("content", ""))
        if not content:
            continue

        x = int(width * text_spec.get("x_percent", 8) / 100)
        y = int(height * text_spec.get("y_percent", 5) / 100)
        max_w = int(width * text_spec.get("max_width_percent", 84) / 100)
        color = text_spec.get("color_hex", "#FFFFFF")
        font_file = text_spec.get("font_file", "WorkSans-Bold.ttf")
        size = int(height * text_spec.get("size_percent", 5) / 100)
        align = text_spec.get("align", "left")

        # Load font with fallback chain
        font = None
        font_path = os.path.join(FONTS_DIR, font_file)
        try:
            font = ImageFont.truetype(font_path, size)
        except Exception:
            try:
                font = ImageFont.truetype(os.path.join(FONTS_DIR, "WorkSans-Bold.ttf"), size)
            except Exception:
                font = ImageFont.load_default()

        # Auto-shrink text if it exceeds max width
        bbox = draw.textbbox((0, 0), content, font=font)
        tw = bbox[2] - bbox[0]
        while tw > max_w and size > 10:
            size = int(size * max_w / tw) - 1
            try:
                font = ImageFont.truetype(font_path, size)
            except Exception:
                font = ImageFont.truetype(os.path.join(FONTS_DIR, "WorkSans-Bold.ttf"), size)
            bbox = draw.textbbox((0, 0), content, font=font)
            tw = bbox[2] - bbox[0]

        # Handle alignment
        draw_x = x
        if align == "center":
            draw_x = x + (max_w - tw) // 2
        elif align == "right":
            draw_x = x + max_w - tw

        draw.text((draw_x, y), content, font=font, fill=color)

    # --- Add subtle grain noise ---
    img_rgb = img.convert("RGB")
    arr = np.array(img_rgb, dtype=np.int16)
    noise = np.random.normal(0, 4, arr.shape).astype(np.int16)
    arr = np.clip(arr + noise, 0, 255).astype(np.uint8)
    result = PILImage.fromarray(arr, "RGB")

    buf = io.BytesIO()
    result.save(buf, format="PNG")
    return buf.getvalue()


# ============================================================
# PASS 4 — CRITIQUE (GPT-4o Vision)
# ============================================================

def critique_design(composed_bytes, brief, work_type):
    """GPT-4o sees the final poster and critiques it."""
    img_b64, img_fmt = compress_for_vision(composed_bytes)
    media_type = f"image/{img_fmt}"

    response = httpx.post(
        "https://api.openai.com/v1/chat/completions",
        headers=openai_headers(),
        json={
            "model": "gpt-4o",
            "messages": [{
                "role": "user",
                "content": [
                    {
                        "type": "image_url",
                        "image_url": {
                            "url": f"data:{media_type};base64,{img_b64}"
                        }
                    },
                    {
                        "type": "text",
                        "text": f"""You are a senior design director. Critique this {work_type}.

Brief: {brief}

Score 1-10 on:
1. TEXT READABILITY: Can all text be clearly read?
2. HIERARCHY: Is the title the most prominent element?
3. COMPOSITION: Does text placement work with the image?
4. COMPLETENESS: Is all required text present?
5. OVERALL QUALITY: Does this look professionally designed?

Output JSON:
{{
  "approved": true/false,
  "score": 7,
  "fixes": [
    {{
      "text_index": 0,
      "field": "y_percent|x_percent|color_hex|size_percent|font_file",
      "new_value": "corrected value",
      "reason": "why"
    }}
  ]
}}

Score 7+ = approved. Only flag real problems. Max 3 fixes.
Output ONLY valid JSON."""
                    }
                ]
            }],
            "max_tokens": 1024
        },
        timeout=60.0
    )
    response.raise_for_status()
    text = response.json()["choices"][0]["message"]["content"]
    return parse_json_response(text)


# ============================================================
# MAIN ENDPOINT
# ============================================================

@app.post("/generate")
async def generate_design(request: dict):
    """
    Design generation pipeline:
    1. gpt-image-1: generates poster visual (no text)
    2. GPT-4o Vision: sees image, outputs text placement JSON
    3. PIL: renders text with real fonts
    4. GPT-4o Vision: critiques result, suggests fixes
    5. PIL: applies fixes if needed (one round max)
    """
    prompt = request.get("prompt", "")
    work_type = request.get("work_type", "poster")

    try:
        # PASS 1 — Generate poster visual
        print("PASS 1: Generating poster image...")
        image_bytes = generate_poster_image(prompt, work_type)
        print(f"PASS 1 complete: {len(image_bytes)} bytes")

        # PASS 2 — Text placement
        print("PASS 2: Getting text placement...")
        font_list = "\n".join(f"    - {f}" for f in get_font_list())
        placement = get_text_placement(image_bytes, prompt, work_type, font_list)
        print(f"PASS 2 complete: {len(placement.get('texts', []))} text elements")

        # PASS 3 — Render text
        print("PASS 3: Rendering text on image...")
        composed = render_text_on_image(image_bytes, placement)
        print(f"PASS 3 complete: {len(composed)} bytes")

        # PASS 4 — Critique
        print("PASS 4: Critiquing design...")
        try:
            critique = critique_design(composed, prompt, work_type)
            score = critique.get("score", 7)
            print(f"PASS 4 complete: score={score}, approved={critique.get('approved', True)}")

            # Apply fixes if not approved (one round only)
            if not critique.get("approved", True) and critique.get("fixes"):
                print(f"Applying {len(critique['fixes'])} fixes...")
                for fix in critique["fixes"]:
                    idx = fix.get("text_index")
                    field = fix.get("field")
                    new_val = fix.get("new_value")
                    texts = placement.get("texts", [])
                    if idx is not None and field and new_val is not None and idx < len(texts):
                        # Convert numeric strings to numbers for numeric fields
                        if field in ("x_percent", "y_percent", "size_percent", "max_width_percent"):
                            try:
                                new_val = float(new_val)
                            except (ValueError, TypeError):
                                continue
                        texts[idx][field] = new_val

                composed = render_text_on_image(image_bytes, placement)
                print("Fix round complete")

        except Exception as e:
            # If critique fails, just use the original composition
            print(f"Critique failed (using original): {e}")

        # Compress and return
        out_b64, out_fmt = compress_for_output(composed)
        return {
            "image": out_b64,
            "format": out_fmt
        }

    except Exception as e:
        import traceback
        print(f"Generation failed: {traceback.format_exc()}")
        return {
            "error": str(e),
            "stderr": traceback.format_exc()
        }


@app.get("/health")
async def health():
    fonts = get_font_list()
    openai_available = bool(os.environ.get("OPENAI_API_KEY"))
    return {
        "status": "ok",
        "fonts_loaded": len(fonts),
        "image_generation": "gpt-image-1" if openai_available else "not configured",
        "architecture": "gpt-image-1 + gpt-4o-vision + PIL"
    }
